Web Site/Models/ListingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Web_Site.Models
{
    public class CreateListingViewModel
    {
        [Required]
        [StringLength(200)]
        public string Title { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        public string Body { get; set; }

        //[Required(ErrorMessage = "Your must provide a PhoneNumber")]
        [Display(Name = "Contact Number")]
        [RegularExpression(@"^[\(|\+]?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4,6})$", ErrorMessage = "Not a valid Phone number")]
        public string ContactNumber { get; set; }

        //[Required(ErrorMessage = "Your must provide a Price")]
        [DataType(DataType.Currency, ErrorMessage = "Not a valid Price")]
        public Decimal Price { get; set; }

        [Required]
        public DateTime Date { get; set; }

        [Required]
        public int CategoryId { get; set; }

        [Required]
        public int TownId { get; set; }
    }
}

Web Site/Models/Listings.cs
 using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Web_Site.Models
{
    public class Listings
    {
        public  Listings()
        {
            this.Date=DateTime.Now;
            this.Files = new List<File>();
        }
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(200)]
        public string Title  { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        public string Body { get; set; }

        //[Required(ErrorMessage = "Your must provide a PhoneNumber")]
        [Display(Name ="Contact Number")]
        [RegularExpression(@"^[\(|\+]?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4,6})$", ErrorMessage = "Not a valid Phone number")]
        public string ContactNumber { get; set; }

        //[Required(ErrorMessage = "Your must provide a Price")]
        [DataType(DataType.Currency, ErrorMessage = "Not a valid Price")]
        public Decimal Price { get; set; }

        [Required]
        public DateTime Date { get; set; }

        public string Author_Id { get; set; }

        [ForeignKey("Author_Id")]
        public ApplicationUser Author { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }

        public virtual ICollection<File> Files { get; set; }

        public int CategoryId { get; set; }
        public virtual Categories Category { get; set; }

        public int TownId { get; set; }
        public virtual Towns Town { get; set; }
    }
}

Web Site/Controllers/ListingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Web_Site.Models;
using System.Web.UI.WebControls;
using System.Collections;

namespace Web_Site.Controllers
{
    public class ListingsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Listings
        public ActionResult Index(string searchBy, string search)
        {
            if (searchBy != null && searchBy.Equals("Title"))
            {
                return View("Search",
                    db.Listings.Include(p => p.Author)
                    .Where(l => l.Title.ToLower().Contains(search.ToLower()) || search == null)
                    .ToList());
            }
            else if (searchBy != null && searchBy.Equals("Author"))
            {
                return View("Search",
                    db.Listings.Include(p => p.Author)
                        .Where(l => l.Author.UserName.ToLower().Contains(search.ToLower()) || search == null)
                        .ToList());
            }
            else if (searchBy != null && searchBy.Equals("Town"))
            {
                return View("Search",
                    db.Listings.Include(p => p.Author)
                        .Where(l => l.Town.Town.ToLower().Contains(search.ToLower()) || search == null)
                        .ToList());
            }
            else
            {
                return View(db.Listings.Include(p => p.Author).ToList());
            }
        }
        public ActionResult SortingByTown(int? id)
        {
            return View(db.Listings.Include(c => c.Author).Where(t => t.TownId == id).ToList());
        }


        public ActionResult SelectedCategorie(int? id)
        {
            var cat = db.Listings.Include(c => c.Author)
                .Where(c => c.CategoryId == id)
                .ToList();
            return View(cat);
        }

        // GET: Listings/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Listings listings = db.Listings.Include(l => l.Author).Single(l => l.Id == id);
            if (listings == null)
            {
                return HttpNotFound();
            }
            return View(listings);
        }

        // GET: Listings/Create
        [Authorize]
        public ActionResult Create()
        {

            return View();
        }

        // POST: Listings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateListingViewModel listings, IEnumerable<HttpPostedFileBase> files)
        {
            if (ModelState.IsValid)
            {
                UserManager<ApplicationUser> UserManager =
                    new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
                ApplicationUser user = UserManager.FindById(this.User.Identity.GetUserId());
                var listing = new Listings { Title = listings.Title, Body = listings.Body, Author = user, Price = listings.Price, ContactNumber = listings.ContactNumber, TownId = listings.TownId, CategoryId = listings.CategoryId };
                var allowedExtensions = new[] { ".jpg", ".png", ".gif" };
                foreach (var file in files)
                {
                    if (file != null)
                    {
                        string extension = file.FileName.Substring(file.FileName.LastIndexOf(".")).ToLower();
                        if (!allowedExtensions.Contains(extension))
                        {
                            TempData["notice"] = "Select .jpg, .png or .gif files format";
                            return View(listing);
                        }
                        else if (file.ContentLength > 1024 * 1024)
                        {
                            TempData["notice"] = "Select files less than 2MB";
                            return View(listing);
                        }
                    }
                    if (file != null && file.ContentLength > 0)
                    {
                        var image = new File
                        {
                            FileName = System.IO.Path.GetFileName(file.FileName),
                            ContentType = file.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(file.InputStream))
                        {
                            image.Content = reader.ReadBytes(file.ContentLength);
                        }
                        listing.Files.Add(image);
                    }
                }
                db.Listings.Add(listing);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(listings);
        }

        // GET: Listings/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Listings listings = db.Listings.Find(id);
            listings = db.Listings.Include(l => l.Files).SingleOrDefault(l => l.Id == id);
            if (listings == null)
            {
                return HttpNotFound();
            }
            // Check If User is Admin or it's the author of the Listing
            if (User.IsInRole("Admin"))
            {
                return View(listings);
            }
            if (User.Identity.GetUserId() != listings.Author_Id)
            {
                return View("Error");
            }
            return View(listings);
        }

        // POST: Listings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Body,Date,CategoryId,TownId,Price,ContactNumber")] Listings listings, IEnumerable<HttpPostedFileBase> files)
        {

            string request = Request.Form["check"];

            var tempListing = listings;

            listings = db.Listings.Include(l => l.Files).SingleOrDefault(l => l.Id == listings.Id);
            listings.Title = tempListing.Title;
            listings.Body = tempListing.Body;
            listings.Date = tempListing.Date;
            listings.Comments = tempListing.Comments;
            listings.TownId = tempListing.TownId;
            listings.Price = tempListing.Price;
            listings.CategoryId = tempListing.CategoryId;
            listings.ContactNumber = tempListing.ContactNumber;

            if (ModelState.IsValid)
            {
                var allowedExtensions = new[] { ".jpg", ".png", ".gif" };
                foreach (var file in files)
                {
                    if (file != null)
                    {
                        string extension = file.FileName.Substring(file.FileName.LastIndexOf(".")).ToLower();
                        if (!allowedExtensions.Contains(extension))
                        {
                            TempData["notice"] = "Select .jpg, .png or .gif files format";
                            return View(listings);
                        }
                        else if (file.ContentLength > 1024 * 1024)
                        {
                            TempData["notice"] = "Select files less than 2MB";
                            return View(listings);
                        }
                    }
                    if (file != null && file.ContentLength > 0)
                    {
                        var image = new File
                        {
                            FileName = System.IO.Path.GetFileName(file.FileName),
                            ContentType = file.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(file.InputStream))
                        {
                            image.Content = reader.ReadBytes(file.ContentLength);
                        }
                        listings.Files.Add(image);
                    }
                }

                if (request != null)
                {
                    int[] actionArgs = request.Split(',').Select(int.Parse).ToArray(); ;
                    foreach (int fileIdToRemove in actionArgs)
                    {
                        db.Files.Remove(listings.Files.First(f => f.FileId == fileIdToRemove));
                    }
                }

                db.Entry(listings).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction($"Details/{listings.Id}");
            }

            return View(listings);
        }

        // GET: Listings/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Listings listings = db.Listings.Find(id);
            if (listings == null)
            {
                return HttpNotFound();
            }
            // Check If User is Admin or it's the author of the Listing
            if (User.IsInRole("Admin"))
            {
                return View(listings);
            }
            if (User.Identity.GetUserId() != listings.Author_Id)
            {

Web Site/Views/Listings/Create.cshtml
@model Web_Site.Models.CreateListingViewModel
@{
    ViewBag.Title = "Create";

    var db = new ApplicationDbContext();
    var categories = db.Categories.ToList();
    List<SelectListItem> categoryList = new List<SelectListItem>();
    foreach (var category in categories)
    {
        categoryList.Add(new SelectListItem
        {
            Text = category.Category,
            Value = category.Id.ToString()
        });
    }

    var towns = db.Towns.ToList();
    List<SelectListItem> townList = new List<SelectListItem>();
    foreach (var town in towns)
    {
        townList.Add(new SelectListItem
        {
            Text = town.Town,
            Value = town.Id.ToString()
        });
    }
}
<h2>Create</h2>

@using (Html.BeginForm("Create", "Listings", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-horizontal">
        <h4>Listings</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => Model.CategoryId, "Choose a category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.CategoryId, categoryList, "Select", new { @class = "btn btn-default dropdown-toggle" })
                 @Html.ValidationMessageFor(model => Model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => Model.TownId, "Choose a town", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.TownId, townList, "Select", new { @class = "btn btn-default dropdown-toggle" })
                @Html.ValidationMessageFor(model => Model.TownId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new {htmlAttributes = new {@class = "form-control", @rows = "10"}})
                @Html.ValidationMessageFor(model => model.Body, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Images", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="files" multiple />
                @if (TempData["notice"] != null)
                {
                    <div class="text-danger">@TempData["notice"]</div>
                }
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web Site/Views/Listings/Delete.cshtml
@model Web_Site.Models.Listings

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Listings</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Web Site/Views/Listings/Details.cshtml
@using Web_Site.Classes
@model Web_Site.Models.Listings

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Listings</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Town)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Town.Town)
        </dd>

        <dt>
            @Html.Label("Photo")
        </dt>

        <dd>
            @if (Model.Files.Count > 0)
            {
                var file = Model.Files.FirstOrDefault(f => f.FileId > 0);
                <div class="imagePhoto">
                    <img src="~/File?id=@file.FileId" />
                </div>
            }
            else
            {
                <i>No uploaded photo</i>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            <textarea class="form-control text-box multi-line valid" disabled="disabled" rows="20">@Html.DisplayFor(model => model.Body)</textarea>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author.Email)
        </dt>

        <dd>
            @if (Model.Author == null)
            {
                <i>(No Email)</i>
            }
            else
            {
                @Html.DisplayFor(model => model.Author.Email)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>

        <dd>
            @if (Model.ContactNumber == null)
            {
                <i>(Is not provided contact number)</i>
            }
            else
            {
                @Html.DisplayFor(model => model.ContactNumber)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @if (Model.Author != null)
            {
                @Model.Author.UserName
            }
            else
            {
                <i>(No Author)</i>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>
    <div>
        @if (Model.Files.Count > 0)
        {
            <p>
                <b>@Html.DisplayNameFor(model => model.Files)</b>
            </p>
            <br />
            foreach (var file in Model.Files)
            {
                <div class="imageDiv">
                    <a href="javascript:;" onClick="ShowPopup(@file.FileId)">
                        <img src="~/File?id=@file.FileId" />
                    </a>  
                </div>
                <br />
            }
        }
        else
        {
            @Html.Label("No Uploaded Images", new { @class = "control-label col-md-2" })
            <br />
        }
    </div>
    <div class="comments-details">
        <h1>Comments</h1>
        @if (Model.Comments.Count > 0)
            {
                foreach (var c in Model.Comments)
                {
                <div class="comments-box">
                    @if (c.Author != null)
                    {
                        <h3>@c.Author.FullName</h3>
                        <i>Commented on @c.Date</i>
                    }
                    else
                    {
                        <h3>No Author</h3>
                        <i>Commented on @c.Date</i>
                    }
                    
                    <div id="comment_text">
                        <p>@c.Text</p>
                    </div>
                </div>
            }
        }
        else
        {
            <i>(No Comments)</i>
        }
    </div>
</div>
<p>
    @if (User.IsInRole("Admin") || User.Identity.Name == Model.Author.UserName)
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) @:|
        @Html.ActionLink("Delete", "Delete", new { id = Model.Id }) @:|
    }
    @Html.ActionLink("Back to List", "Index")
</p>

Web Site/Views/Listings/Edit.cshtml
@model Web_Site.Models.Listings

@{
    ViewBag.Title = "Edit";

    var db = new ApplicationDbContext();
    var categories = db.Categories.ToList();
    List<SelectListItem> categoryList = new List<SelectListItem>();
    foreach (var category in categories)
    {
        categoryList.Add(new SelectListItem
        {
            Text = category.Category,
            Value = category.Id.ToString()
        });
    }

    var towns = db.Towns.ToList();
    List<SelectListItem> townList = new List<SelectListItem>();
    foreach (var town in towns)
    {
        townList.Add(new SelectListItem
        {
            Text = town.Town,
            Value = town.Id.ToString()
        });
    }
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Listings", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Listings</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => Model.CategoryId, "Choose a category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.CategoryId, categoryList, Model.CategoryId.ToString(), new { @class = "btn btn-default dropdown-toggle" })
                @Html.ValidationMessageFor(model => Model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => Model.TownId, "Choose a town", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.TownId, townList, Model.TownId.ToString(), new { @class = "btn btn-default dropdown-toggle" })
                @Html.ValidationMessageFor(model => Model.TownId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control", @rows = "10" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Upload New Images", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="files" multiple/>
                @if (TempData["notice"] != null)
                {
                    <div class="text-danger">@TempData["notice"]</div>
                }
            </div>
        </div>

        @if (Model.Files.Count > 0)
        {
            foreach (var file in Model.Files)
            {
                <div class="form-group">
                    @Html.Label("Image", new { @class = "control-label col-md-2" })
                    <div class="imageDiv">
                        <img src="~/File?id=@file.FileId"/>
                        <p><input type="checkbox" name="check" value="@file.FileId"/> <b>Check to remove image</b></p>
                    </div>                   
                </div>
            }
        }
        else
        {
            @Html.Label("No Uploaded Images", new { @class = "control-label col-md-2" })
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web Site/Views/Listings/Index.cshtml
@using Web_Site.Classes
@model IEnumerable<Web_Site.Models.Listings>

@{
    ViewBag.Title = "Index";
}
<h2>Listings</h2>

<p>
    @using (Html.BeginForm("Index", "Listings", FormMethod.Get))
    {
        <b>Search by: </b>@Html.RadioButton("searchBy", "Title", true) <text>Title</text>
        @Html.RadioButton("searchBy", "Author")
        <text>Author's UserName</text>
        @Html.RadioButton("searchBy", "Town") <text>Town</text>
        <br />
        @Html.TextBox("search") <input type="submit" value="Search" />
    }
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th>
           @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Town)
        </th>
        <th>Actions</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Utils.CutText(item.Body)
            </td>
            <td>
                <a href="/Listings/SelectedCategorie/@item.CategoryId" >@item.Category.Category</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @if (item.Author != null)
                {
                    @item.Author.UserName
                    if (item.Author.FullName != null)
                    {
                        <br />
                        <i>(@item.Author.FullName)</i>
                    }
                }
                else
                {
                    <i>(No Author)</i>
                }
            </td>
            <td class="comment_col">
                @if (item.Comments.Count > 0)
                {
                    <div>@item.Comments.Count</div>
                }
                else
                {
                    <i>(No Comments)</i>
                }
            </td>
            <td>
                <a href="/Listings/SortingByTown/@item.TownId">@item.Town.Town</a>
            </td>
            <td align="center">
                @{ var data = new ItemIdAuthor { ItemId = item.Id, Author = item.Author.UserName }; }
                @Html.Partial("ActionMenu", data)
            </td>
        </tr>
    }
</table>